set(_CATKIN_CURRENT_PACKAGE "ros_project_vision")
set(ros_project_vision_VERSION "0.0.0")
set(ros_project_vision_MAINTAINER "latreides <latreides@todo.todo>")
set(ros_project_vision_PACKAGE_FORMAT "2")
set(ros_project_vision_BUILD_DEPENDS )
set(ros_project_vision_BUILD_EXPORT_DEPENDS )
set(ros_project_vision_BUILDTOOL_DEPENDS "catkin")
set(ros_project_vision_BUILDTOOL_EXPORT_DEPENDS )
set(ros_project_vision_EXEC_DEPENDS )
set(ros_project_vision_RUN_DEPENDS )
set(ros_project_vision_TEST_DEPENDS )
set(ros_project_vision_DOC_DEPENDS )
set(ros_project_vision_URL_WEBSITE "")
set(ros_project_vision_URL_BUGTRACKER "")
set(ros_project_vision_URL_REPOSITORY "")
set(ros_project_vision_DEPRECATED "")