set(_CATKIN_CURRENT_PACKAGE "ros_project_description")
set(ros_project_description_VERSION "0.0.0")
set(ros_project_description_MAINTAINER "latreides <latreides@todo.todo>")
set(ros_project_description_PACKAGE_FORMAT "2")
set(ros_project_description_BUILD_DEPENDS )
set(ros_project_description_BUILD_EXPORT_DEPENDS )
set(ros_project_description_BUILDTOOL_DEPENDS "catkin")
set(ros_project_description_BUILDTOOL_EXPORT_DEPENDS )
set(ros_project_description_EXEC_DEPENDS )
set(ros_project_description_RUN_DEPENDS )
set(ros_project_description_TEST_DEPENDS )
set(ros_project_description_DOC_DEPENDS )
set(ros_project_description_URL_WEBSITE "")
set(ros_project_description_URL_BUGTRACKER "")
set(ros_project_description_URL_REPOSITORY "")
set(ros_project_description_DEPRECATED "")