#!/usr/bin/env python
from __future__ import division
import rospy
from sensor_msgs.msg import Image
from std_msgs.msg import String
from cv_bridge import CvBridge
import cv2
import numpy as np
image_converter = CvBridge()

ORANGE_BGR_UPPER = np.array((10, 255, 255), dtype='uint8')
ORANGE_BGR_LOWER = np.array((0, 25, 100), dtype='uint8')

BLUE_BGR_UPPER = np.array((245, 3, 16), dtype='uint8')
BLUE_BGR_LOWER = np.array((44, 0, 5), dtype='uint8')

BOX_BGR_UPPER = np.array((88, 171, 201), dtype='uint8')
BOX_BGR_LOWER = np.array((55, 98, 98), dtype='uint8')

g_orange_left_frac = 0
g_orange_right_frac = 0

g_blue_left_frac = 0
g_blue_right_frac = 0

g_box_left_frac = 0
g_box_right_frac = 0

def camera_callback(gz_image):

  """ Detect the color orange.
  
  rosmsg show sensor_msgs/Image
  """
  global g_orange_left_frac
  global g_orange_right_frac

  #rospy.loginfo('Image is {} by {}'.format(gz_image.width, gz_image.height))
  cv_image = image_converter.imgmsg_to_cv2(gz_image, "bgr8")
  
  orange_mask = cv2.inRange(cv_image, ORANGE_BGR_LOWER, ORANGE_BGR_UPPER)
  orange_image = cv2.bitwise_and(cv_image, cv_image , mask=orange_mask)
  
  orange_left = orange_mask[int(orange_mask.shape[0] * 0.54):, :int(orange_mask.shape[1]/2)]
  orange_right = orange_mask[int(orange_mask.shape[0] * 0.54):, int(orange_mask.shape[1]/2):]

  orange_count_left = cv2.countNonZero(orange_left)
  orange_count_right = cv2.countNonZero(orange_right)
    
  g_orange_left_frac = float(orange_count_left) /  float(orange_left.size)
  g_orange_right_frac = float(orange_count_right) /  float(orange_right.size)
  
  
  global g_blue_left_frac
  global g_blue_right_frac
  
  blue_mask = cv2.inRange(cv_image, BLUE_BGR_LOWER, BLUE_BGR_UPPER)
  blue_image = cv2.bitwise_and(cv_image, cv_image, mask=blue_mask)
  
  blue_left = blue_mask[int(blue_mask.shape[0] * 0.54):, :int(blue_mask.shape[1]/2)]
  blue_right = blue_mask[int(blue_mask.shape[0] * 0.54):, int(blue_mask.shape[1]/2):]
  
  blue_count_left = cv2.countNonZero(blue_left)
  blue_count_right = cv2.countNonZero(blue_right)
  
  g_blue_left_frac = float(blue_count_left) /  float(blue_left.size)
  g_blue_right_frac = float(blue_count_right) /  float(blue_right.size)
  
  
  global g_box_left_frac
  global g_box_right_frac
  
  box_mask = cv2.inRange(cv_image, BOX_BGR_LOWER, BOX_BGR_UPPER)
  box_image = cv2.bitwise_and(cv_image, cv_image, mask=box_mask)
  
  box_left = box_mask[int(box_mask.shape[0] * 0.55):, :int(box_mask.shape[1]/2)]
  box_right = box_mask[int(box_mask.shape[0] * 0.55):, int(box_mask.shape[1]/2):]
  
  box_count_left = cv2.countNonZero(box_left)
  box_count_right = cv2.countNonZero(box_right)
  
  g_box_left_frac = float(box_count_left) /  float(box_left.size)
  g_box_right_frac = float(box_count_right) /  float(box_right.size)
  
  print(g_box_left_frac, g_box_right_frac)
  #print (g_orange_left_frac, g_orange_right_frac, g_blue_left_frac, g_blue_right_frac)
  cv2.imshow('camera', np.hstack([cv_image, box_image]))
  cv2.waitKey(1)

def orange_detector():
  rospy.init_node('orange_detector', anonymous=True)
  rospy.Subscriber('/ros_project/camera1/image_raw', Image, camera_callback)

def run_orange_publisher():
  global g_orange_left_frac
  global g_orange_right_frac
  orange_publisher = rospy.Publisher('/ros_project/orange_frac', String, queue_size=1)
  rate = rospy.Rate(1)
  while not rospy.is_shutdown():
    orange_fracs = '{} {} {} {} {} {}'.format(g_orange_left_frac, g_orange_right_frac, g_blue_left_frac, g_blue_right_frac, g_box_left_frac, g_box_right_frac)
    orange_publisher.publish(orange_fracs)
    rate.sleep()

if __name__ == '__main__':
  orange_detector()
  
  try:
    run_orange_publisher()
  except rospy.ROSInterruptException:
    pass
    
    
