set(_CATKIN_CURRENT_PACKAGE "ros_project_control")
set(ros_project_control_VERSION "0.0.0")
set(ros_project_control_MAINTAINER "latreides <latreides@todo.todo>")
set(ros_project_control_PACKAGE_FORMAT "2")
set(ros_project_control_BUILD_DEPENDS )
set(ros_project_control_BUILD_EXPORT_DEPENDS )
set(ros_project_control_BUILDTOOL_DEPENDS "catkin")
set(ros_project_control_BUILDTOOL_EXPORT_DEPENDS )
set(ros_project_control_EXEC_DEPENDS )
set(ros_project_control_RUN_DEPENDS )
set(ros_project_control_TEST_DEPENDS )
set(ros_project_control_DOC_DEPENDS )
set(ros_project_control_URL_WEBSITE "")
set(ros_project_control_URL_BUGTRACKER "")
set(ros_project_control_URL_REPOSITORY "")
set(ros_project_control_DEPRECATED "")