ros_project:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  leftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_joint_left
    pid: {p: 100.0, i: 0.01, d: 10.0}
  rightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_joint_right
    pid: {p: 100.0, i: 0.01, d: 10.0}
