set(_CATKIN_CURRENT_PACKAGE "ros_project_gazebo")
set(ros_project_gazebo_VERSION "0.0.0")
set(ros_project_gazebo_MAINTAINER "latreides <latreides@todo.todo>")
set(ros_project_gazebo_PACKAGE_FORMAT "2")
set(ros_project_gazebo_BUILD_DEPENDS )
set(ros_project_gazebo_BUILD_EXPORT_DEPENDS )
set(ros_project_gazebo_BUILDTOOL_DEPENDS "catkin")
set(ros_project_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(ros_project_gazebo_EXEC_DEPENDS )
set(ros_project_gazebo_RUN_DEPENDS )
set(ros_project_gazebo_TEST_DEPENDS )
set(ros_project_gazebo_DOC_DEPENDS )
set(ros_project_gazebo_URL_WEBSITE "")
set(ros_project_gazebo_URL_BUGTRACKER "")
set(ros_project_gazebo_URL_REPOSITORY "")
set(ros_project_gazebo_DEPRECATED "")